config/routes.rb
WebGeofeed::Application.routes.draw do
  resources :careers

  match 'search' => 'public#search', :as => :search

   root :to => 'public#search'

end

app/models/career.rb
class Career < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  # GET /careers
  # GET /careers.json
  def index
    @search = Career.search(params[:search])
    @careers = @search.all   # load all matching records

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @careers }
    end
  end

  # GET /careers/1
  # GET /careers/1.json
  def show
    @career = Career.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @career }
    end
  end

  # GET /careers/new
  # GET /careers/new.json
  def new
    @career = Career.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @career }
    end
  end

  # GET /careers/1/edit
  def edit
    @career = Career.find(params[:id])
  end

  # POST /careers
  # POST /careers.json
  def create
    @career = Career.new(params[:career])

    respond_to do |format|
      if @career.save
        format.html { redirect_to @career, notice: 'Career was successfully created.' }
        format.json { render json: @career, status: :created, location: @career }
      else
        format.html { render action: "new" }
        format.json { render json: @career.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /careers/1
  # PUT /careers/1.json
  def update
    @career = Career.find(params[:id])

    respond_to do |format|
      if @career.update_attributes(params[:career])
        format.html { redirect_to @career, notice: 'Career was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @career.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /careers/1
  # DELETE /careers/1.json
  def destroy
    @career = Career.find(params[:id])
    @career.destroy

    respond_to do |format|
      format.html { redirect_to careers_url }
      format.json { head :ok }
    end
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  protect_from_forgery


  def search
    if session[:tip].nil?
      session[:tip] = @tip = true 
    end
    
    @tipos_instituciones = [] + Career.all.collect(&:tipo_institucion).uniq
    @instituciones = [] + Career.all.collect{|c| c.institucion.truncate(32)}.uniq
    @carreras = [] + Career.all.collect{|c|c.carrera.truncate(43)}.uniq
    @search = Career.search(params[:search])
    @careers = @search.all.shift(25)
    @max_range = Career.maximum("promedio_arancel")
    @min_range = Career.minimum("promedio_arancel")
    @map_feed_url = "http://maps.google.com/maps/api/staticmap?size=512x512&markers=size:mid|color:red|"
    markers = ''
    @careers.each do |career|
      markers += "#{career.direccion_casa_central},Chile|"
    end
    @map_feed_url += (markers + "&mobile=true&sensor=false")
    params[:search] ||= Hash.new
    @search.promedio_arancel_greater_than ||= @min_range
    @search.promedio_arancel_less_than ||= @max_range
    @search.promedio_psu_less_than ||= 850
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @careers }
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def short_url long_url
   @bitly ||= Bitly.new('mediadecision','R_f5fb9f543e1257eb09d83d546e141f2b')
   if Rails.env.development?
     long_url = 'http://www.google.cl'
   end
   page_url = @bitly.shorten(long_url)
   page_url.shorten
  end
 
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/views/careers/_form.html.erb
<%= form_for(@career) do |f| %>
  <% if @career.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@career.errors.count, "error") %> prohibited this career from being saved:</h2>

      <ul>
      <% @career.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_institucion %><br />
    <%= f.text_field :tipo_institucion %>
  </div>
  <div class="field">
    <%= f.label :carrera %><br />
    <%= f.text_field :carrera %>
  </div>
  <div class="field">
    <%= f.label :institucion %><br />
    <%= f.text_field :institucion %>
  </div>
  <div class="field">
    <%= f.label :areas_conocimiento %><br />
    <%= f.text_field :areas_conocimiento %>
  </div>
  <div class="field">
    <%= f.label :empleabilidad_primer_ano %><br />
    <%= f.text_field :empleabilidad_primer_ano %>
  </div>
  <div class="field">
    <%= f.label :empleabilidad_segundo_ano %><br />
    <%= f.text_field :empleabilidad_segundo_ano %>
  </div>
  <div class="field">
    <%= f.label :region_mayor_numero_titulados %><br />
    <%= f.text_field :region_mayor_numero_titulados %>
  </div>
  <div class="field">
    <%= f.label :n_matriculados_primer_ano %><br />
    <%= f.text_field :n_matriculados_primer_ano %>
  </div>
  <div class="field">
    <%= f.label :n_matriculados_total %><br />
    <%= f.text_field :n_matriculados_total %>
  </div>
  <div class="field">
    <%= f.label :estudiantes_municipales %><br />
    <%= f.text_field :estudiantes_municipales %>
  </div>
  <div class="field">
    <%= f.label :estudiantes_particular_subvencionado %><br />
    <%= f.text_field :estudiantes_particular_subvencionado %>
  </div>
  <div class="field">
    <%= f.label :estudiantes_particular_pagado %><br />
    <%= f.text_field :estudiantes_particular_pagado %>
  </div>
  <div class="field">
    <%= f.label :porcentaje_estudiantes_psu %><br />
    <%= f.text_field :porcentaje_estudiantes_psu %>
  </div>
  <div class="field">
    <%= f.label :promedio_psu %><br />
    <%= f.text_field :promedio_psu %>
  </div>
  <div class="field">
    <%= f.label :promedio_nem %><br />
    <%= f.text_field :promedio_nem %>
  </div>
  <div class="field">
    <%= f.label :tasa_retencion_primer_ano %><br />
    <%= f.text_field :tasa_retencion_primer_ano %>
  </div>
  <div class="field">
    <%= f.label :tasa_retencion_segundo_ano %><br />
    <%= f.text_field :tasa_retencion_segundo_ano %>
  </div>
  <div class="field">
    <%= f.label :n_titulados %><br />
    <%= f.text_field :n_titulados %>
  </div>
  <div class="field">
    <%= f.label :duracion_esperada %><br />
    <%= f.text_field :duracion_esperada %>
  </div>
  <div class="field">
    <%= f.label :duracion_real %><br />
    <%= f.text_field :duracion_real %>
  </div>
  <div class="field">
    <%= f.label :promedio_arancel %><br />
    <%= f.text_field :promedio_arancel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/careers/edit.html.erb
<h1>Editing career</h1>

<%= render 'form' %>

<%= link_to 'Show', @career %> |
<%= link_to 'Back', careers_path %>

app/views/careers/index.html.erb
<h1>Listing careers</h1>

<table>
  <tr>
    <th>Tipo institucion</th>
    <th>Carrera</th>
    <th>Institucion</th>
    <th>Areas conocimiento</th>
    <th>Empleabilidad primer ano</th>
    <th>Empleabilidad segundo ano</th>
    <th>Region mayor numero titulados</th>
    <th>N matriculados primer ano</th>
    <th>N matriculados total</th>
    <th>Estudiantes municipales</th>
    <th>Estudiantes particular subvencionado</th>
    <th>Estudiantes particular pagado</th>
    <th>Porcentaje estudiantes psu</th>
    <th>Promedio psu</th>
    <th>Promedio nem</th>
    <th>Tasa retencion primer ano</th>
    <th>Tasa retencion segundo ano</th>
    <th>N titulados</th>
    <th>Duracion esperada</th>
    <th>Duracion real</th>
    <th>Promedio arancel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @careers.each do |career| %>
  <tr>
    <td><%= career.tipo_institucion %></td>
    <td><%= career.carrera %></td>
    <td><%= career.institucion %></td>
    <td><%= career.areas_conocimiento %></td>
    <td><%= career.empleabilidad_primer_ano %></td>
    <td><%= career.empleabilidad_segundo_ano %></td>
    <td><%= career.region_mayor_numero_titulados %></td>
    <td><%= career.n_matriculados_primer_ano %></td>
    <td><%= career.n_matriculados_total %></td>
    <td><%= career.estudiantes_municipales %></td>
    <td><%= career.estudiantes_particular_subvencionado %></td>
    <td><%= career.estudiantes_particular_pagado %></td>
    <td><%= career.porcentaje_estudiantes_psu %></td>
    <td><%= career.promedio_psu %></td>
    <td><%= career.promedio_nem %></td>
    <td><%= career.tasa_retencion_primer_ano %></td>
    <td><%= career.tasa_retencion_segundo_ano %></td>
    <td><%= career.n_titulados %></td>
    <td><%= career.duracion_esperada %></td>
    <td><%= career.duracion_real %></td>
    <td><%= career.promedio_arancel %></td>
    <td><%= link_to 'Show', career %></td>
    <td><%= link_to 'Edit', edit_career_path(career) %></td>
    <td><%= link_to 'Destroy', career, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Career', new_career_path %>

app/views/careers/new.html.erb
<h1>New career</h1>

<%= render 'form' %>

<%= link_to 'Back', careers_path %>

app/views/careers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tipo institucion:</b>
  <%= @career.tipo_institucion %>
</p>

<p>
  <b>Carrera:</b>
  <%= @career.carrera %>
</p>

<p>
  <b>Institucion:</b>
  <%= @career.institucion %>
</p>

<p>
  <b>Areas conocimiento:</b>
  <%= @career.areas_conocimiento %>
</p>

<p>
  <b>Empleabilidad primer ano:</b>
  <%= @career.empleabilidad_primer_ano %>
</p>

<p>
  <b>Empleabilidad segundo ano:</b>
  <%= @career.empleabilidad_segundo_ano %>
</p>

<p>
  <b>Region mayor numero titulados:</b>
  <%= @career.region_mayor_numero_titulados %>
</p>

<p>
  <b>N matriculados primer ano:</b>
  <%= @career.n_matriculados_primer_ano %>
</p>

<p>
  <b>N matriculados total:</b>
  <%= @career.n_matriculados_total %>
</p>

<p>
  <b>Estudiantes municipales:</b>
  <%= @career.estudiantes_municipales %>
</p>

<p>
  <b>Estudiantes particular subvencionado:</b>
  <%= @career.estudiantes_particular_subvencionado %>
</p>

<p>
  <b>Estudiantes particular pagado:</b>
  <%= @career.estudiantes_particular_pagado %>
</p>

<p>
  <b>Porcentaje estudiantes psu:</b>
  <%= @career.porcentaje_estudiantes_psu %>
</p>

<p>
  <b>Promedio psu:</b>
  <%= @career.promedio_psu %>
</p>

<p>
  <b>Promedio nem:</b>
  <%= @career.promedio_nem %>
</p>

<p>
  <b>Tasa retencion primer ano:</b>
  <%= @career.tasa_retencion_primer_ano %>
</p>

<p>
  <b>Tasa retencion segundo ano:</b>
  <%= @career.tasa_retencion_segundo_ano %>
</p>

<p>
  <b>N titulados:</b>
  <%= @career.n_titulados %>
</p>

<p>
  <b>Duracion esperada:</b>
  <%= @career.duracion_esperada %>
</p>

<p>
  <b>Duracion real:</b>
  <%= @career.duracion_real %>
</p>

<p>
  <b>Promedio arancel:</b>
  <%= @career.promedio_arancel %>
</p>


<%= link_to 'Edit', edit_career_path(@career) %> |
<%= link_to 'Back', careers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Media Decisión! - Compara universidades en Chile usando datos públicos.</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
  <script type="text/javascript" src="/fancybox/jquery.easing-1.3.pack.js"></script>
  <script type="text/javascript" src="/jquery.qtip.js"></script> 
  <link rel="stylesheet" href="/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script>

$(document).ready(function() {

    $('table thead th[title]').qtip({
        position: {
              corner: {
                 target: 'bottomMiddle',
                 tooltip: 'center'
              }
           },
           style: { 
                 width: 200,
                 padding: 5,
                 // background: '#A2D959',
                 color: 'black',
                 textAlign: 'center',
                 border: {
                    width: 7,
                    radius: 5,
                    // color: '#A2D959'
                 },
                 tip: 'topMiddle',
                 name: 'green' // Inherit the rest of the attributes from the preset dark style
              }
    })
    
	/* This is basic - uses default settings */
	
	$("a.fancy_box").fancybox({
		'transitionIn'	:	'elastic',
		'transitionOut'	:	'elastic',
		'speedIn'		:	600, 
		'speedOut'		:	200, 
		'overlayShow'	:	false
	});

});
</script>
</body>
</html>